---
- name: Run roles and SCAP audit
  hosts: dunab13-VM
  remote_user: DunaAdmin
  become: yes # true
  # roles:
  #   - "sudo"
  #   - ...
  tasks:
    - name: Install SCAP
      yum:
        name:
          - openscap-scanner
          - scap-security-guide
        state: present

    - name: Run SCAP audit with ANSSI profile
      command:
        cmd: >-
            oscap xccdf eval
            --profile xccdf_org.ssgproject.content_profile_anssi_bp28_minimal
            --results /tmp/anssi_results.xml
            --report /tmp/anssi_report.html
            /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
      register: oscap_result
      ignore_errors: yes

    - name: Save audit report
      fetch:
        src: /tmp/anssi_report.html
        dest: ../audit_reports/audit_report.xml
        flat: yes
      tags:
      - verification